version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./cache-db:/data
      - /etc/localtime:/etc/localtime:ro

  app:
    image: faucet-app
    container_name: faucet-app
    build: .
    ports:
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro