version: '3.8'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./faucet-db:/data/db
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./cache-db:/data 